# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: CyberJutsu
    url: https://cyberjutsu.io
  - name: Blog
    url: https://blog.cyberjutsu.io
  - name: Learn
    url: https://learn.cyberjutsu.io
  - name: Job
    url: https://jobs.cyberjutsu.io

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.timoxoszt.me
  # baseUrl: /sites-uptime
  logoUrl: https://jobs.cyberjutsu.io/favicon.ico
  name: Upptime
  introTitle: "**CyberJutsu** webpentest healthcheck."
  introMessage: This is a status page which uses **real-time** data
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
